---
layout: default
title: Registro por carga masiva de muestras y resultado de Test de antígeno
description: Carga Masiva - Antigenos
parent: Profesional tomador de muestras - Registro
nav_order: 4
---

## Introducción

El siguiente instructivo explica los pasos necesarios para realizar cargas masivas de resultados de antígeno a través de la plataforma PNTM. Los usuarios podrán acceder a la sección de cargas masivas, descargar una planilla base con los campos solicitados, ingresar los datos requeridos y cargar el archivo de forma satisfactoria.

## Instrucciones de la carga masiva
   ![[Pasted image 20230215103637.png]]
   _Foto: Sección de cargas masivas por la interfaz_
   
1.  Es necesario acceder al módulo de "Cargas Masivas" dentro de la plataforma y seleccionar la sección "Antígeno".
2.   En el botón desplegable "Estructura del archivo a cargar" se pueden visualizar los campos solicitados en la Planilla Base de toma de muestras, incluyendo el nombre de la columna, el tipo de dato, la descripción y las restricciones correspondientes.
3. La Planilla Base se encuentra disponible para su descarga en formato Excel, a través del botón "Descargar base" ubicado debajo de la descripción de los campos.
4. Para ingresar los datos correspondientes a cada muestra, es necesario incluir al menos todos los datos obligatorios en la fila 2 del archivo Excel, y guardar el archivo una vez completado.
5. En la plataforma, se debe seleccionar el botón "Seleccionar archivo" y elegir el archivo deseado para luego hacer clic en "Subir archivo" y completar la carga de forma satisfactoria.

## Estructura del archivo a cargar

La tabla que se presenta a continuación muestra la estructura de los datos que se deben rellenar en el archivo Excel. Cada columna representa un tipo de dato y la descripción que indica su función dentro del formulario. Además, se especifican las restricciones que se deben cumplir en cada columna para asegurar que la carga masiva sea procesada correctamente. Los usuarios deben incluir al menos todos los datos obligatorios descritos en la sección "Campos Solicitados".

| Columna                      | Tipo de dato | Descripción                                                                                                                                                                                                                                                                                                                                            | Restricciones                                                                                                                                                                                                                                                                                                                                             |
|------------------------------|--------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| run_pasaporte*               | Varchar      | Numero de identificacion del paciente                                                                                                                                                                                                                                                                                                                  | Obligatorio En caso de ser RUN debe ser valido                                                                                                                                                                                                                                                                                                            |
| paciente_tipodoc*            | Varchar      | tipo de dumento de identificacion del paciente Ejemplo: RUN PASAPORTE DNI PAIS DE ORIGEN SIN DOCUMENTACION N° FICHA CLINICA                                                                                                                                                                                                                            | Obligatorio Debe estar dentro de los valores aceptados:  1. RUN: run_pasaporte 2. PASAPORTE: run_pasaporte y paciente_ext_paisorigen 3. DNI PAIS DE ORIGEN: run_pasaporte y paciente_ext_paisorigen 4. SIN DOCUMENTACION: No se debe asignar valor a run_pasaporte y paciente_ext_paisorigen 5. N° FICHA CLINICA: run_pasaporte y paciente_ext_paisorigen |
| paciente_nombres*            | Varchar      | Nombres del paciente                                                                                                                                                                                                                                                                                                                                   | Obligatorio                                                                                                                                                                                                                                                                                                                                               |
| paciente_ap_pat*             | Varchar      | Apellido paterno del paciente                                                                                                                                                                                                                                                                                                                          | Obligatorio                                                                                                                                                                                                                                                                                                                                               |
| paciente_ap_mat*             | Varchar      | Apellido Materno del paciente                                                                                                                                                                                                                                                                                                                          | Obligatorio                                                                                                                                                                                                                                                                                                                                               |
| paciente_direccion*          | Varchar      | Direccion del paciente                                                                                                                                                                                                                                                                                                                                 | Obligatorio Ejemplo: Avenida El Bosque.                                                                                                                                                                                                                                                                                                                   |
| paciente_telefono*           | Numero       | Numero de telefono del paciente                                                                                                                                                                                                                                                                                                                        | Obligatorio                                                                                                                                                                                                                                                                                                                                               |
| paciente_edad*               | Date         | Edad del paciente                                                                                                                                                                                                                                                                                                                                      | Obligatorio                                                                                                                                                                                                                                                                                                                                               |
| paciente_comuna*             | Numero       | Codigo de la comuna del paciente                                                                                                                                                                                                                                                                                                                       | Obligatorio Debe ser una comuna valida del maestro                                                                                                                                                                                                                                                                                                        |
| paciente_numero_direccion*   | Varchar      | Numero de identificador de la calle/avenida                                                                                                                                                                                                                                                                                                            | Obligatorio Ejemplo: 130                                                                                                                                                                                                                                                                                                                                  |
| paciente_depto_direccion*    | Varchar      | Numero de identificador del dpto. casa del paciente                                                                                                                                                                                                                                                                                                    | No obligatorio Ejemplo: 22A                                                                                                                                                                                                                                                                                                                               |
| paciente_poblacion_villa*    | Varchar      | Población de residencia del paciente                                                                                                                                                                                                                                                                                                                   | Obligatorio Ejemplo: Talca                                                                                                                                                                                                                                                                                                                                |
| paciente_via_direccion*      | Varchar      | tipo de via residencia del paciente                                                                                                                                                                                                                                                                                                                    | Obligatorio debe estar dentro del maestro via_dirección Ejemplo: 1                                                                                                                                                                                                                                                                                        |
| paciente_mail*               | Varchar      | Dirección de correo electrónico                                                                                                                                                                                                                                                                                                                        | Obligatorio                                                                                                                                                                                                                                                                                                                                               |
| paciente_ext_paisorigen*     | Numero       | Codigo del pais de origen del paciente                                                                                                                                                                                                                                                                                                                 | Obligatorio si paciente_tipodoc es igual a "PASAPORTE ", "DNI PAIS DE ORIGEN", "N° FICHA CLINICA" o "SIN DOCUMENTACION" Debe ser un codigo valido del maestro paises                                                                                                                                                                                      |
| rut_profesional_responsable* | Varchar      | RUN del responable de la muestra                                                                                                                                                                                                                                                                                                                       | Obligatorio Debe existir en la base de profesionales                                                                                                                                                                                                                                                                                                      |
| rut_medico                   | Varchar      | RUN del medico que solicita la muestra                                                                                                                                                                                                                                                                                                                 | Opcional                                                                                                                                                                                                                                                                                                                                                  |
| cod_deis*                    | Varchar      | Codigo DEIS del Establecimiento                                                                                                                                                                                                                                                                                                                        | Obligatorio Debe existir en el maestro cod_deis                                                                                                                                                                                                                                                                                                           |
| epivigila*                   | Varchar      | Codigo epivigila                                                                                                                                                                                                                                                                                                                                       | No obligatorio                                                                                                                                                                                                                                                                                                                                            |
| tipo_muestra*                | Varchar      | Tipo de muestra realizada Ejemplo: Tórula nasofaríngea Tórula nasal                                                                                                                                                                                                                                                                                    | Obligatorio Debe ser: Tórula nasofaríngea o Tórula nasal                                                                                                                                                                                                                                                                                                  |
| fecha_muestra_date*          | Date         | Fecha en que se crea la solicitud                                                                                                                                                                                                                                                                                                                      | Obligatorio                                                                                                                                                                                                                                                                                                                                               |
| busqueda_activa*             | Boolean      | Tipo de busqueda Valores: 0 = No 1 = Si                                                                                                                                                                                                                                                                                                                | Obligatorio                                                                                                                                                                                                                                                                                                                                               |
| resultado*                   | Varchar      | Valor del resultado de la muestra                                                                                                                                                                                                                                                                                                                      | Obligatorio Debe ser: Positivo, Negativo, No concluyente                                                                                                                                                                                                                                                                                                  |
| codigo_marca_test*           | Varchar      | Marca de la prueba                                                                                                                                                                                                                                                                                                                                     | Obligatorio debe estar dentro del maestro marca_test                                                                                                                                                                                                                                                                                                      |
| no_ingresa_pais              | Boolean      | Marca que indica ingreso efectivo al país Valores: 0 = SI ingresa al país 1 = NO ingresa al país                                                                                                                                                                                                                                                       | No es Obligatorio                                                                                                                                                                                                                                                                                                                                         |
| estrategia                   | Texto        | Indica la estrategia asociada a la muestra de antígeno Valores cuando busqueda activa es 1: BAC Punto de Entrada BAC Brotes BAC Autotest  Valores cuando busqueda activa es 0: Sintomáticos Residencias Sanitarias  Atención médica                                                                                                                    | No es Obligatorio                                                                                                                                                                                                                                                                                                                                         |
| subestrategia                | Texto        | Indica la subestrategia asociada a la muestra de antígeno con estrategia BAC Brotes Valores: BAC Escolar BAC ELEAM BAC Mejor Niñez/SENAME BAC Centros Penitenciarios BAC Laboral OAL/AD/Centros de Salud BAC centro de diálisis BAC entorno prioritario BAC otros hogares BAC recintos de FFAA BAC viviendas colectivas y campamentos BAC comunitarios | No es Obligatorio                                                                                                                                                                                                                                                                                                                                         |
| observacion_muestra          | Varchar      | Observación resultado antígeno                                                                                                                                                                                                                                                                                                                         | Opcional                                                                                                                                                                                                                                                                                                                                                  |

[[Errores en la carga masiva en la plataforma Nacional de Toma de Muestras (PNTM)]]
[[Descarga de datos maestros - Antigenos]]

